name: memote history

on: push

jobs:
  memote-history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # MEMOTE wants to fetch all branches
        with:
          fetch-depth: 0


      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install memote
        run: pip install -r code/requirements/ci-requirements.txt

      - name: Checkout repo for gh-pages branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: gh-pages
          path: gh-pages-repo

      # - name: Convert model
      #   run: |
      #     touch .env
      #     python -c 'import code.io as io; model = io.read_yeast_model(make_bigg_compliant=True); io.write_yeast_model(model)'

      - name: Memote short run
        run: |
          memote run --ignore-git --skip-unchanged --solver-timeout 30

      - name: Compute Memote history on push
        run: |
          # Generate the history report on the deployment branch
          git config --global user.name "memote-bot"
          memote report history --filename="gh-pages-repo/history_report.html"

      - name: Fetch async changes in gh-pages
        run: |
          cd gh-pages-repo
          git pull

      - name: Auto-commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: memote-bot
          commit_message: "chore: update memote history report"
          file_pattern: history_report.html
          branch: gh-pages
          repository: gh-pages-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
