name: memote run

on: pull_request

jobs:
  memote-run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/metabolicatlas/memote-docker:0.13
      volumes:
        - ${{ github.workspace }}:/project:rw
      options: --workdir /project

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env
        run: |
          touch .env
          cd /project
          pip install -r code/requirements/ci-requirements.txt
          python -c 'import code.io as io; model = io.read_yeast_model(make_bigg_compliant=True); io.write_yeast_model(model)'
          memote run --ignore-git --solver-timeout 30
